# Generated by Django 3.1.5 on 2021-01-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocustomer',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
